export const config = {
  /** Set to a number to force a specific BPM (bypasses auto-detection) */
  bpmOverride: null as number | null,

  /** Offset in seconds — shifts the beat grid forward/back */
  beatOffset: 0,

  /** Min beats to hold a clip before cutting */
  minBeats: 2,

  /** Max beats to hold a clip before cutting */
  maxBeats: 8,

  /**
   * Weighted cut patterns — each [beats, weight] pair.
   * Higher weight = more likely to be picked.
   * e.g. hold for 4 beats (common), 2 beats (quick), 8 beats (long hold)
   */
  cutWeights: [
    [2, 2],   // quick cut — occasional
    [4, 5],   // one bar — most common
    [6, 3],   // bar and a half — medium
    [8, 2],   // two bars — let it breathe
  ] as [number, number][],

  /** How many clips to randomly select per session */
  clipCount: 25,

  /** Path to the song file in public/ */
  songPath: '/YESSRO.m4a',

  /** Path to the clip manifest generated by convert-clips.sh */
  manifestPath: '/clips/manifest.json',
};
